<?php require_once('./templates/header.phtml'); ?>

<?php foreach($categories as $category) : ?>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">ID: <?php echo $category->id_categoria ?></h5>
            <h5 class="card-title">Nombre: <?php echo $category->nombre_categoria ?></h5>
        </div>
    </div>
<?php endforeach ?>

<?php require_once('./templates/footer.phtml'); ?>